#!/bin/sh

workspace_dir=$1
output_dir=$2

s3_bucket_name="heroku-buildpack-ruby"
vendor_url="https://s3.amazonaws.com/$s3_bucket_name"
maven_version="3.1.1"

curl "http://jruby.org.s3.amazonaws.com/downloads/$VERSION/jruby-src-$VERSION.tar.gz" -s -o - | tar zxf -

cd jruby-$VERSION
if [ $VERSION="1.7.5" ]; then
	package_file="/tmp/buildpack_*/vendor/package.rb"
	cp $package_file lib/ruby/shared/rubygems
fi
curl http://mirror.nexcess.net/apache/maven/maven-3/3.1.1/binaries/apache-maven-$maven_version-bin.tar.gz -s -o - | tar xzf -

var=$(echo $RUBY_VERSION | awk -F"." '{print $1,$2,$3}')
set -- $var
major=$1
minor=$2
patch=$3

apache-maven-$maven_version/bin/mvn -Djruby.default.ruby.version=$major.$minor
rm bin/*.bat
rm bin/*.dll
rm bin/*.exe
ln -s jruby bin/ruby
mv bin $output_dir
mv lib $output_dir
