#!/bin/sh

workspace_dir=$1
output_dir=$2

s3_bucket_name="heroku-buildpack-ruby"
vendor_url="https://s3.amazonaws.com/$s3_bucket_name"
ant_version="1.9.2"

curl "http://jruby.org.s3.amazonaws.com/downloads/$VERSION/jruby-src-$VERSION.tar.gz" -s -o - | tar zxf -

cd jruby-$VERSION
curl http://www.trieuvan.com/apache//ant/binaries/apache-ant-$ant_version-bin.tar.gz -s -o - | tar xzf -

cd bin
curl "$vendor_url/jruby-launcher-1.0.12-java.tgz" -s -o - | tar zxf -
cd ..

var=$(echo $RUBY_VERSION | awk -F"." '{print $1,$2,$3}')
set -- $var
major=$1
minor=$2
patch=$3

apache-ant-$ant_version/bin/ant -Djruby.default.ruby.version=$major.$minor
rm bin/*.bat
rm bin/*.dll
rm bin/*.exe
ln -s jruby bin/ruby
mv bin $output_dir
mv lib $output_dir
